import { readFileSync, writeFileSync } from 'node:fs';

const manifest = JSON.parse(readFileSync('./src/utils/manifest.json', 'utf-8'));

// manifest.json groups by variant, e.g. { filled: [...], round: [...] }
// flatten + dedupe (component names are already unique per the -alt collision logic)
const allNames = [...new Set(Object.values(manifest).flat())];

const entries = allNames
  .map((name) => `  ${name}: () => import('../${name}.js'),`)
  .join('\n');

const out = `// AUTO-GENERATED by generate-loaders.mjs — do not edit by hand
export const iconLoaders: Record<string, () => Promise<any>> = {
${entries}
};
`;

writeFileSync('./src/utils/loaders.ts', out);
console.log(`Wrote ${allNames.length} icon loaders to src/utils/loaders.ts`);